### ISSUE TITLE
Importing directories (with index.ts files) does not work

### ISSUE THREAD

**Issue by henhal** [ts-docs/ts-docs#22]
**Describe the bug**

Imported directories (where directory/index.ts is implicitly referred to) are not resolved, but assumed to be .ts files, instead of traversing down into `directory/index.ts` etc.

**To Reproduce**

With this directory structure:
```
foo
  |- index.ts
```

And this import:
```
import Foo from './foo'
```

I only get 

```
(node:19450) UnhandledPromiseRejectionWarning: Error: Couldn't find file '<snip>/foo.ts'
    at TypescriptExtractor.run (<snip>/node_modules/@ts-docs/extractor/dist/extractor/index.js:106:23)
```
**Expected behavior**

Imported directories with index files should be supported

**Comment by GoogleFeud** [comment]
Interesting - can I see your ts-docs options? The error can only come from [here](https://github.com/ts-docs/ts-extractor/blob/aa84bb3ada3cae55eaa57f02dbf9dc63f4476246/src/extractor/index.ts#L135), which has nothing to do with resolving imports. 

I suspect one of your entry points is set to `<snip>/foo`, but you have to include the filename, so it has to be `<snip>/foo/index` or `<snip>/foo/index.ts`

**Comment by henhal** [comment]
My options were default, I just started trying the tool out and thought it looked promising, but encountered this pretty much straight away.
I'm not sure I understood your last paragraph, are you saying my code needs to explicitly import _files_? Importing a module via a directory path which implicitly translates to directory/index.ts is obviously very common...? Or did you refer to entry points passed to tsdoc? If I remember correctly, I simply installed and ran 

```
$ tsdoc src
```

**Comment by GoogleFeud** [comment]
> I'm not sure I understood your last paragraph, are you saying my code needs to explicitly import files? Importing a module via a directory path that implicitly translates to directory/index.ts is very common...? Or did you refer to entry points passed to tsdoc? If I remember correctly, I simply installed and ran

Entry points passed to the ts-docs options, that's why I asked to see the options you used. Entry points work a little differently in ts-docs - each entry point must be pointing to a file.

**Comment by henhal** [comment]
Ok thanks.
I have no idea why, but I tried again now with simply `ts-docs src/index.ts` and it worked fine now. I'm not even sure what differed from the last time. Sorry.

**Comment by GoogleFeud** [comment]
All good, glad it's working. Just a heads up - If you're documenting an application rather than a library there's the [documentImports](https://tsdocs.xyz/pages/Guides/Options.html#documentimports) option which documents all items from all imported files. By default, ts-docs only goes through the exports of the entry point. 

The `entryPoints` option works differently than other documentation tools like `typedoc` - every entry point must point to a file that is from a different npm library/application (so every file should be under a different `package.json` file ). The main goal of ts-docs is to make it easy to document monorepos.

**Comment by henhal** [comment]
Understood, thanks! For now, my intention was to use it for stand-alone library modules.
