### ISSUE TITLE
CLI script does not work on Linux

### ISSUE THREAD

**Issue by JakeStanger** [ts-docs/ts-docs#5]
**Describe the bug**

The shebang in the script ends with a carriage return line feed (`CRLF`, `\r\n`) which is not valid in Unix-land. This means `/usr/bin/env` cannot parse it.

**To Reproduce**

Run the installed script:

Using a package manager:
```
 yarn ts-docs                                                    
yarn run v1.22.15
$ /home/jake/Programming/Work/WebpartLibrary/node_modules/.bin/ts-docs
/usr/bin/env: ‘node\r’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Or directly:
```
λ node_modules/.bin/ts-docs src/index.ts
/usr/bin/env: ‘node\r’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

**Expected behavior**

The file should contain Unix-like line endings (ie just `LF`, `\n`) ideally throughout, but at least for the shebang.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Shell: zsh
 - Version: 0.1.2

**Additional Information**

This can be worked around by starting the script with node:

```
λ node node_modules/.bin/ts-docs src/index.ts
```

**Comment by GoogleFeud** [comment]
Good catch!

**Comment by GoogleFeud** [comment]
I know I said it's been fixed in the release notes, but can someone make sure because there's no easy way for me to check :)

**Comment by JakeStanger** [comment]
Try running:
```
git config --global core.autocrlf false
```

**Comment by GoogleFeud** [comment]
Alright! Can you check it out now?

**Comment by GoogleFeud** [comment]
Well, I just realised that the typescript compiler always changes the line endings depending on the platform, so it doesn't matter what the line endings are in the original file. There's an option to change that, though!

**Comment by GoogleFeud** [comment]
Nice! Closing this!
