### ISSUE TITLE
`const` arrow funcs should be treated as normal funcs/methods

### ISSUE THREAD

**Issue by JakeStanger** [ts-docs/ts-docs#6]
Currently any const, regardless of type, is displayed as its source code. 

In most cases this makes sense but for arrow funcs, this can get messy. 

![image](https://user-images.githubusercontent.com/5057870/137352370-c6594b98-f957-4fb9-9079-00d58085703e.png)

There are a few cases to prefer const arrow funcs over regular functions/methods, such as `this` binding or easier typing. I believe arrow functions should be automatically detected and treated as if they're regular functions, or class methods.

**Comment by GoogleFeud** [comment]
I strongly agree! I've been working on a fix for the last few days - It's also going to render array / object literals, and it'll also attempt to render types returned from functions! 

Expect this fixed by the end of the week!
