### ISSUE TITLE
Obey stripInternal compiler option

### ISSUE THREAD

**Issue by andrew-w-ross** [ts-docs/ts-docs#8]
**Is your feature request related to a problem? Please describe.**

Some properties need to be public so other parts of the module can read them but undocumented to external packages.

**Describe the solution you'd like**

If a `@internal` js-doc comment is found don't emit documentation for it if the `stripInternal` flag is set to true.

**Additional context**

[Typedoc has an excludeInternal option but it seems more natural to use the compiler option already there.](https://typedoc.org/guides/options/#excludeinternal)

Let me know if you like the idea and I'll make a pr.

**Comment by GoogleFeud** [comment]
Heads up: just implemented the feature, it's gonna be in the upcoming 0.2.0 release :).
